apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-{{INSTANCE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener-{{INSTANCE}}
  template:
    metadata:
      labels:
        app: url-shortener-{{INSTANCE}}
    spec:
      containers:
      - name: url-shortener
        image: url-shortener:latest
        ports:
        - containerPort: 5001
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: ""
        - name: MYSQL_DATABASE
          value: "url_short"
        - name: FLASK_PORT
          value: "{{PORT}}"
