apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service-{{INSTANCE}}
spec:
  type: LoadBalancer
  ports:
  - port: {{EXTERNAL_PORT}}
    targetPort: {{PORT}}
  selector:
    app: url-shortener-{{INSTANCE}}